### ISSUE TITLE
Upstreaming into nixpkgs

### ISSUE THREAD

**Issue by onny** [nix-community/nix-snapd#18]

**Comment by io12** [comment]
I don't know if I want to do this. Snaps are really designed to work mostly on Ubuntu, and the further you go from Ubuntu, snaps are less and less likely to work well. NixOS is very different from Ubuntu, and there are a lot of hacks to get it to mostly work a lot of the time, so I don't know if it's stable enough for nixpkgs. It's an experimental thing that might work for most snaps, but snapd doesn't do enough containerization to be as portable as something like Flatpak. For example, [nextcloud-snap only supports Ubuntu](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Why-Ubuntu-is-the-only-supported-distro) for these kinds of reasons.
